export const LIST_CONTACTS = 'LIST_CONTACTS';
export const LIST_CONTACTS_SUCCESS = 'LIST_CONTACTS_SUCCESS';
export const LIST_CONTACTS_FAILURE = 'LIST_CONTACTS_FAILURE';
export const LIST_ALL_CONTACTS = 'LIST_ALL_CONTACTS';
export const SET_CONTACT_DEFAULTS = 'SET_CONTACT_DEFAULTS';
